# Site settings
title: Levi9 Symfony Training
email: m.labinskyi@levi9.com
description: |
  Levi9 internal Symfony training.
  The leading PHP framework to create websites and web applications.
  Embracing and promoting professionalism, best practices, standardization and interoperability of applications.
baseurl: "/sf-levi9" # the subpath of your site, e.g. /blog/
url: "http://e-moe.github.io" # the base hostname & protocol for your site
github:
    - e-moe
    - maxmode
twitter_username:

# Build settings
markdown: kramdown
